name: ascend_arena
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  audioplayers: ^6.7.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.2
  image_picker: ^1.2.3
  path_provider: ^2.1.6
  pinput: ^6.0.2
  record: ^6.2.1
  supabase_flutter: ^2.17.1
  fl_chart: ^0.68.0
  image_cropper: ^12.2.1
  flutter_animate: ^4.5.0
  confetti: ^0.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^7.3.1
  workmanager: ^0.10.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
